---
title: "GIS fundamentals:"
format: html
callout-appearance: simple
---

Hey, fellow programmers and geospatial nerds. Josiah here. It’s been a while since my last video. The subject for this video is one a topic that feels so rudimentary, but is often skipped over. It's a fundamental that folks like myself don't truly learn until later in life. It’s got to do with vector data: points lines and polygons. 

I’ve been doing geospatial analysis in some way, shape, or form since 2014. Only recently have I felt I truly understood vector data. We're going to walk through the [simple feature standard](https://www.ogc.org/standard/sfa/) from the [Open Geospatial Consortium (OGC)](https://www.ogc.org/).


:::{.callout-note}
The OGC is a neutral organization who's sole purpose is to bolster and organize the geospatial community through "publicly available and open standards" that drive innovation and ensure interoperability across tech stacks.[^ogc]
:::


[^ogc]: https://www.ogc.org/about/

Let's think about all the different types of data we can gather about the world around us: locations of cities, roads, UFO sightings, rivers, houses, and quite literally anything that can be observed in the world around us (including things on other planets). All of this data can be represented by simple geometry features such as points, lines, and polygons. The Simple Feature Standard gives us a way to do that. The SF standard makes it easy to describe geometries in a consistent way using _geometric primitives_ so that they can be understood no matter what programming language or software is being used.

:::{.callout-tip}
A geometric primitive is an _atomic_ unit. It is the smallest unit that a shape can be broken down into. Geometric primitives are the building blocks for all other geometries. 
:::


## OGC and Standards 

> "This standard enumerates the requirements for defining and representing geographic features in geographic information systems, applications and transmittable data formats." 


The simple feature standard (SF) defines how vector data is recorded and transmitted. Of course data need to be recorded and transmitted, but is a whole standard really necessary? What does it mean to be a standard and why are they important? Well, that gets to the core of why the OGC exists if you ask me. 

:::{.aside} 
There could, and maybe should, be a whole video dedicated to the OGC and the work that they do. I’ll provide links in the description and this will be available as a blog on my website.
:::

OGC standards formalize how something should be built, function, or behave. Because they are generally agreed upon and fairly exhaustive, they ensure that users can expect the same behavior regardless of what tool or language they may be using. Standards are critical for the open source community and commercial entities that rely upon open source. These standards define, in words, how software should behave.


## Simple Feature Standard

The simple feature (SF) standard is broken up into two parts. The first defines the "common architecture" and the second defines how a SQL interface should interact with the simple features. We don't care about SQL today. Only about the first part. 

We're going to get quite specific. So get ready for a journey. 






