# Generated by the vetiver package; edit with care
library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

b <- board_folder(path = "models")
v <- vetiver_pin_read(b, "childcare-costs-xgb")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v, debug = TRUE)
}
